### ISSUE TITLE
Bad Gateway Error

### ISSUE THREAD

**Issue by aruneral01** [gbrian/grafana-simple-sql-datasource#1]
Hi Gustavo

I am getting an error below when i am connecting Grafana to a MSQL2016 Instance thru the grafana-simple-sql-datasource plugin . Can you please alert me how to progress.

Error
{"data":"","status":502,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/1","data":{"type":"test","body":null,"url":null},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Bad Gateway"}

Thanks again for prompt response

arun

**Comment by gbrian** [comment]
Hi @aruneral01,

Updated the serverside script so you can check using your browser.
Run serverside script: `node sqlproxyserver.js`
Test on your browser navigating to `http://myserver:port/?con=mssql://user:name@server/database` you must get a {"status":"sucess"} response.

Found and old issue in Grafana, https://github.com/grafana/grafana/issues/6790 please be sure to be using latest Grafana version.

I've updated documentation: https://github.com/gbrian/grafana-simple-sql-datasource/blob/master/README.md

Hope this helps.

**Comment by gbrian** [comment]
@aruneral01 any update?

**Comment by gbrian** [comment]
@aruneral01 ,
Fixed! Finally found thet grafana was removing the "query string" part of the url when proxied.
Please download latest version and fix the url on the datasource by removing the "?" separator, should be enough.

![image](https://user-images.githubusercontent.com/767180/29856763-4289919a-8d55-11e7-9d25-9566085824bd.png)
