### ISSUE TITLE
NPM Install fails on dependency of contextify package

### ISSUE THREAD

**Issue by dcvice1967** [gbrian/grafana-simple-sql-datasource#12]
One or more of the packages this data source depends on is dependent in the Contextify npm package. However, Contextify is no longer compatible with the latest versions of node and npm. Is it possible to remove this dependency?

**Comment by gbrian** [comment]
Hi @dcvice1967 , 
Yep, think so but need to find `who` asks for `Contextify` :( 
BTW is this an stopper for you now?

**Comment by dcvice1967** [comment]
Looking to to some testing of Grafana against an internal sql server db.
Not critical at the moment.

Thanks,

**Comment by markmnl** [comment]
I think you need g++ for Contextify. Will have to install that on system first.

**Comment by gbrian** [comment]
Sorry, automatically closing old issues after several fixes. Please reopen if the problem persists.
