### ISSUE TITLE
Fixing multiple template parsing

### ISSUE THREAD

**Issue by buiductri** [gbrian/grafana-simple-sql-datasource#13]
Hi Brian, it's me, Billy again :)
I hit this issue when working with multiple values of template.
![image](https://user-images.githubusercontent.com/22960369/30573246-ed03c344-9d1c-11e7-9e18-4412873c162e.png)

And after playing around with the source code, I found out that this one causing this (dunno why although (cwl))
![image](https://user-images.githubusercontent.com/22960369/30573336-721ed442-9d1d-11e7-8c1f-81f504ca4620.png)

Then this is the result after remove the "distributed"
![image](https://user-images.githubusercontent.com/22960369/30573368-9c935374-9d1d-11e7-83b0-db05d223f005.png)

I prefer this way since I can parse it using T-SQL. How about your opinion?

Thanks and Best Regard,
Billy B.

**Comment by gbrian** [comment]
Hi @bily-gates,

Sorry for late answer. I have an open request to Grafana to change the way they "decompress" multivalue.
I don't see an easy way without affecting Grafana core but sure we can add extra settings to the metric with different "multi-value" options. 
Probably someone will prefer `'DB233','DB234'` than can be set on a ` Field in ($DBS)` statement.... dunno
BTW if this way works for you is nice but forces parsing on SQL (that I don't like :(  as SQL Server is quite limitated on this)

How will work for you the `'A','B','C'` mode?

Thanks

**Comment by buiductri** [comment]
Hi @gbrian.

Actually, as a DBA, I already have a way to parse the `'{DB233,DB234}'` string and currently use it for the workaround. And I prefer it than the `'DB233', 'DB234'` because of security best practices. I currently enclose the `SELECT` statement with a stored procedure, so I am afraid that may not work in my case even though it is way better in `SELECT` request. (sad)

For your and others reference, here is the code I used:
```
DECLARE	@servers NVARCHAR(MAX) = '{DB233, DB234}';
SELECT	@servers = CASE WHEN LEFT(@servers, 1) = '{' THEN SUBSTRING(@servers, 2, LEN(@servers)) ELSE @servers END;
SELECT	@servers = CASE WHEN RIGHT(@servers, 1) = '}' THEN SUBSTRING(@servers, 1, LEN(@servers) - 1) ELSE @servers END;
	
WITH cte AS (
	SELECT	'start'		= CAST(1 AS INT)
		,	'finish'	= CASE WHEN CHARINDEX(',', @servers, 1) = 0 THEN LEN(@servers) + 1 ELSE CHARINDEX(',', @servers, 1) END
	UNION ALL
	SELECT	'start'		= CAST(cte.finish + 1 AS INT)
		,	'finish'	= CASE WHEN CHARINDEX(',', @servers, cte.finish + 1) = 0 THEN LEN(@servers) + 1 ELSE CHARINDEX(',', @servers, cte.finish + 1) END
	FROM	cte
	WHERE	cte.finish < LEN(@servers)
)
SELECT	LTRIM(RTRIM(SUBSTRING(@servers, cte.start, cte.finish - cte.start)))
FROM	cte
WHERE	LTRIM(RTRIM(SUBSTRING(@servers, cte.start, cte.finish - cte.start))) <> '';
```

The other pro of enclosing the request with SP is you actually don't need to update the dashboard everytime you make a small adjustment. Believe me, my dashboard was over hundred versions and I was trouble tracking all of the version until decided to enclose all of them to a SP. Woala, since then only 8 versions included testing and bug fixing. Sound good, right? (lol)

Let me know if you have any *cool* idea for make it better.

Best Regard,
Billy B.

**Comment by gbrian** [comment]
@bily-gates ,

I see. :) But correct me if I'm wrong, same as you do with `{A,B,C}` can be done with `('A','B','C')` ...don't you?
```

DECLARE	@servers NVARCHAR(MAX) = '(''DB233'', ''DB234'',''DB234'')';
SELECT	@servers = CASE WHEN LEFT(@servers, 1) = '(' THEN SUBSTRING(@servers, 2, LEN(@servers)) ELSE @servers END;
SELECT	@servers = CASE WHEN RIGHT(@servers, 1) = ')' THEN SUBSTRING(@servers, 1, LEN(@servers) - 1) ELSE @servers END;
	
WITH cte AS (
	SELECT	'start'		= CAST(1 AS INT)
		,	'finish'	= CASE WHEN CHARINDEX(',', @servers, 1) = 0 THEN LEN(@servers) + 1 ELSE CHARINDEX(',', @servers, 1) END
	UNION ALL
	SELECT	'start'		= CAST(cte.finish + 1 AS INT)
		,	'finish'	= CASE WHEN CHARINDEX(',', @servers, cte.finish + 1) = 0 THEN LEN(@servers) + 1 ELSE CHARINDEX(',', @servers, cte.finish + 1) END
	FROM	cte
	WHERE	cte.finish < LEN(@servers)
)
SELECT LEFT(RIGHT(value, LEN(value)-1), LEN(value)-2), REPLACE(value, '''', '')
FROM (
SELECT	LTRIM(RTRIM(SUBSTRING(@servers, cte.start, cte.finish - cte.start))) as value
FROM	cte
WHERE	LTRIM(RTRIM(SUBSTRING(@servers, cte.start, cte.finish - cte.start))) <> ''
) T;
```
Then is up to the guy doing the query...I understand your concern about security but I think is out of the scope right now.

So do you agree with going with the `('A','B','C')` ? Iin future versions we can manage with different formats or who knows something like `$Servers:{'%s'}` or whatever ...

**Comment by buiductri** [comment]
Hi @gbrian,
Yes, it can be done the same way with 2 single quote pass into the variable. But then it cannot work with `SELECT` anymore. You can take a look at this example:
(1)
```
EXECUTE Grafana_sp_GetData @server = '$servers'
```

(2)
```
SELECT *
FROM Grafana_Data
WHERE server_name IN ($server)
```

If we parse using `'DB233','DB234'` then (1) will not work since it parses like this
```
EXECUTE Grafana_sp_GetData @server = ''DB233','DB234''
                                       ^
```
If we parse using `''DB233'',''DB234''` then (2) won't work
```
SELECT *
FROM Grafana_Data
WHERE server_name IN (''DB233'',''DB234'')
                        ^
```
I am still thinking which way can work for both but no clue yet.

p/s: But for the sake of majority, maybe I just have to use the version that I am currently using now (`{DB233,DB234}`). The version for everyone (`'DB233','DB234'`) may be more general than mine.

**Comment by gbrian** [comment]
@bily-gates ,

There won't be double quotes, just needed for the test and this way only applies when there's more than one value selected.

## Lets say we repeat panel per server:
`SELECT value, metric, time FROM table WHERE Server = '$Servers'` 
_Note that we are adding the quotes as server can be numeric or string_

Becomes
`SELECT value, metric, time FROM table WHERE Server = 'DB233'`

## We do not repeat panel:

**Query mode**
`SELECT value, metric, time FROM table WHERE Server in ($Servers)`
Becomes
`SELECT value, metric, time FROM table WHERE Server in ('DB233','DB234')`

**Store procedure**
`EXECUTE Grafana_sp_GetData @server = '{$Servers}'`
Becomes
`EXECUTE Grafana_sp_GetData @server = '{'DB233','DB234'}'`

So the `(' and `)` symbols can be taken out so you are free to surround the variables.

We are close! :D

**Comment by buiductri** [comment]
Hi @gbrian ,

> Store procedure
> EXECUTE Grafana_sp_GetData @server = '{$Servers}'
> Becomes
> EXECUTE Grafana_sp_GetData @server = '{'DB233','DB234'}'

Sadly, the execute will raise syntax error in this case. The problem is how T-SQL handle the single quote. If we stick to put in single quote, only 1 of 2 above modes can work. :(

**Comment by gbrian** [comment]
Damit! @bily-gates 

Ok, lets do this, please cerate a PR so will apply your woraround and people working like you will benefit but let's keep this thread open so I can fix all others cases. Agree? :)

**Comment by buiductri** [comment]
@gbrian Sorry for my late reply, I have been too busy lately 😿. It's okay with me. I will submit a PR soon. I also want to keep this thread open. Maybe someone who has more caffein than you and me can think of something that work. LOL 🤣

**Comment by gbrian** [comment]
Hi @bily-gates, back to action!
Was re-checking this issue. Do you have time for a recap? 
Thanks in advance

**Comment by buiductri** [comment]
Hi @gbrian , got it. Here is the full investigate result from me during the time. 😄 

First to mention, when grafana applying template, it has some parsing types to apply, which have just described in [this documentation](http://docs.grafana.org/reference/templating/#advanced-formatting-options) since grafana 5.1.

The code originally apply **distributed** template. But to work best, in my case, it should be **glob**. 
Then the template will be parsed like this:
`{DB1, DB2, DB3}`

So in the code of `datasource.js`, the following lines are related:
line 93: `annotationQuery.annotation.query = this.templateSrv.replace(options.annotation.query, {}, 'glob');`
line 145: `return _.assignIn(target, { target: _this.templateSrv.replace(target.target, options.scopedVars, "distributed") });`

And from **grafana 5.1**, we can work around without editing the code by using this variable (template) form: `${server:csv}` or `${server:glob}` instead of `$server`.
The **csv** (only works from 5.1) will be parsed like this: `DB1, DB2, DB3` (without brackets)
