### ISSUE TITLE
What datasource type to use?

### ISSUE THREAD

**Issue by markmnl** [gbrian/grafana-simple-sql-datasource#15]
> Add new datasource Add a new datasource to Grafana and set the url to:

There is no compatible type in the dropdown.. Does one have to install SimpleJson first?

**Comment by markmnl** [comment]
OK figured it out need to put grafana-simple-sql-datasource in /var/lib/grafana/plugins then restart grafana-server. Then will have new data source type: SimpleSql

**Comment by gbrian** [comment]
Sorry, did not see on time. Working fine?
