### ISSUE TITLE
q@1.5.0 invalid : unable to install all packages with npm

### ISSUE THREAD

**Issue by paulcoates** [gbrian/grafana-simple-sql-datasource#18]
I have tried to install this project in a Mac OS and Ubuntu 16.04 environments, in both cases I have been unable to get the dependency 'q' to install with npm.  I can start the server (on a port other than 666) but I every GET requests results in a failure.

Running 'npm list' gives me the following output
── q@1.5.0 invalid
npm ERR! invalid: q@1.5.0 /Users/username/projects/grafana-simple-sql-datasource/node_modules/q

If I run 'npm install q@1.5.0' I get the following error:
grafana-simple-sql-datasource@1.0.0 /opt/sqlproxy/grafana-simple-sql-datasource
└── q@1.5.0  invalid

Any suggestions on how I can work out whether this is my environment, this project or something else?

**Comment by gbrian** [comment]
Hi @paulcoates ,

Looks like `q` module is not present.
Have you run `npm install` on root directory where **package.json** is?

**Comment by paulcoates** [comment]
Hi @gbrian, yes I have a number of times.  It is always successful (although the first time does give some deprecation warnings).  However if I run `npm list` after `npm install` which gives the invalid message:
`└── q@1.5.0 invalid`
`npm ERR! invalid: q@1.5.0 /opt/sqlproxy/grafana-simple-sql-datasource/node_modules/q`

node version 6.11.4
npm version 3.10.10

**Comment by gbrian** [comment]
Hi @paulcoates ,
Looks nodejs / npm related, sadly I can only suggest update to latest version (if possible), is quite strange error and I can not find any info about anyone else complaining :(

Can only think on two options:

- Remove / Reinstall
- Update nodejs/npm

**Comment by sawo1337** [comment]
I had the same problem, edited package.json, line 32 (devDependencies):
Changed     "q": "~1.4.1", to     "q": "^1.4.1",
Apparently, 1.5.x is too far from 1.4.1
The GET error is probably related to a mistake in the documentation. The sample URL provided will never work, because there is an ? missing in it. It has to be http://myserver:port/?con=mssql://user:name@server/database
Took me some time to notice that :)

**Comment by paulcoates** [comment]
> Changed "q": "~1.4.1", to "q": "^1.4.1",

This fixed my issues (along with the typo in the sample URL). Many thanks.

**Comment by gbrian** [comment]
Fixed, many thanks @sawo1337 and @paulcoates 
https://github.com/gbrian/grafana-simple-sql-datasource/commit/909236b4bf647d66cf94d98410e9450f9bd3cc9d
