### ISSUE TITLE
SQL Connector with PIE Chart

### ISSUE THREAD

**Issue by mohanraj1939** [gbrian/grafana-simple-sql-datasource#22]
Hi all,
Thanks for the great plugin.
I have an issue when connecting MS SQL Server with piechart using the connector.
`SELECT COUNT(TAGID), Active
FROM dbo.TAG
GROUP BY Active`
I obtained the clear Output in Table, but when i use the  same code in PIECHART it throws me an error 
"Unable to get Property 'length' of undefined or null reference".
I'm using latest Grafana 4.6.1 & Latest connector which is updated on 12.11.2017.

**Comment by gbrian** [comment]
Sorry, automatically closing old issues after several fixes. Please reopen if the problem persists.
