### ISSUE TITLE
Cannot connect to more than one SQL

### ISSUE THREAD

**Issue by Jaco-P** [gbrian/grafana-simple-sql-datasource#25]
Not sure if it is an issue - but you cannot connect to more than one SQL server at a time. I would like to setup a dashboard across multiple servers....

**Comment by gbrian** [comment]
@Jaco-P Ops, ofc sounds a good idea, I'm testing `codemill` let me try find someone to fix.

codemill$10

**Comment by gbrian** [comment]
Dammit, did not work.. by the way @Jaco-P is a matter of having multiple datasources, isn't it?
Closing issue, please reopen with an example if I'm missing something.
