### ISSUE TITLE
Error running sqlproxyserver.js with nodejs

### ISSUE THREAD

**Issue by swapper82** [gbrian/grafana-simple-sql-datasource#3]
Hi
Anyone have a suggestion on what I might be doing wrong?

```
grafana-simple-sql-datasource/1.0.0/package/dist/serverside# nodejs sqlproxyserver.js

/home/appliance/.npm/grafana-simple-sql-datasource/1.0.0/package/dist/serverside/sqlproxyserver.js:21
        .then(provider => {
                        ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

```

**Comment by c0c00n** [comment]
Hi, 
same here 

node -v v0.10.48
 


node serverside/sqlproxyserver.js

/usr/share/grafana/public/app/plugins/datasource/grafana-simple-sql-datasource/serverside/sqlproxyserver.js:21
        .then(provider => {
                        ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
[root@vlng grafana-simple-sql-datasource]# node debug serverside/sqlproxyserver.js
< debugger listening on port 5858
connecting... ok

< /usr/share/grafana/public/app/plugins/datasource/grafana-simple-sql-datasource/serverside/sqlproxyserver.js:21
<         .then(provider => {
<
<               ^
< SyntaxError: Unexpected token >
<     at Module._compile (module.js:439:25)
<     at Object.Module._extensions..js (module.js:474:10)
<     at Module.load (module.js:356:32)
<     at Function.Module._load (module.js:312:12)
<     at Module.runMain [as _onTimeout] (module.js:497:10)
<     at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
program terminated

**Comment by gbrian** [comment]
Hi @swapper82 , @c0c00n ,

Looks like it does not implements lambdas (Emacs6) probably old nodejs versio.
Is it possible for you to update? Maybe this helps https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

Operating system? 
Got ir running on Debian and Windows without any problems :(
`node -v` drops:

* Debian  `v6.10.0` 
* Windows `v6.9.5` 

Hope this helps

**Comment by c0c00n** [comment]
Hi gbrain,

sorry for the delayed response, holiday. 

Operating system= Linux version 2.6.32-642.el6.x86_64 (mockbuild@worker1.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Tue May 10 17:27:01 UTC 2016

I updated as you mentioned the node. after running nmp install on dist/serverside i got the following error:

npm ERR! Linux 2.6.32-642.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/install/grafana-simple-sql-datasource/dist/serverside/npm-debug.log

**Comment by gbrian** [comment]
Hi @c0c00n, 
Run `npm install` at root folder where `package.json` is located, not on `dist\serverside`

**Comment by c0c00n** [comment]
Hi @gbrian,

followed your advice....

`pwd` /home/install/grafana-simple-sql-datasource

`ll -ltr`
-rw-r--r--   1 root root   2003 Jun 28 10:12 README.md
-rw-r--r--   1 root root   1070 Jun 28 10:12 LICENSE
-rw-r--r--   1 root root   1724 Jun 28 10:12 Gruntfile.js
drwxr-xr-x   6 root root   4096 Jun 28 10:12 dist
-rw-r--r--   1 root root   1426 Jun 28 10:12 package.json
-rw-r--r--   1 root root 398240 Jun 28 10:12 overview.png
drwxr-xr-x   2 root root   4096 Jun 28 10:12 spec
-rw-r--r--   1 root root 152565 Jun 28 10:12 query_editor.png
drwxr-xr-x   6 root root   4096 Jun 28 10:12 src
drwxr-xr-x 333 root root  12288 Jun 28 10:13 node_modules
-rw-r--r--   1 root root 817513 Jun 28 10:13 npm-debug.log

`npm install`
npm ERR! Linux 2.6.32-642.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/install/grafana-simple-sql-datasource/npm-debug.log

`tail -n 20 /home/install/grafana-simple-sql-datasource/npm-debug.log`
38903 verbose cwd /home/install/grafana-simple-sql-datasource
38904 error Linux 2.6.32-642.el6.x86_64
38905 error argv "/usr/bin/node" "/usr/bin/npm" "install"
38906 error node v6.11.0
38907 error npm  v3.10.10
38908 error code ELIFECYCLE
38909 error contextify@0.1.15 install: `node-gyp rebuild`
38909 error Exit status 1
38910 error Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
38910 error Make sure you have the latest version of node.js and npm installed.
38910 error If you do, this is most likely a problem with the contextify package,
38910 error not with npm itself.
38910 error Tell the author that this fails on your system:
38910 error     node-gyp rebuild
38910 error You can get information on how to open an issue for this project with:
38910 error     npm bugs contextify
38910 error Or if that isn't available, you can get their info via:
38910 error     npm owner ls contextify
38910 error There is likely additional logging output above.
38911 verbose exit [ 1, true ]

**Comment by gbrian** [comment]
@c0c00n 
That's what I've found: https://github.com/bevacqua/perfschool/issues/5
Can you please try: `npm install node-gyp-install && ./node_modules/node-gyp-install/bin.js`  fingers crossed!

**Comment by c0c00n** [comment]
@gbrian
 
`npm install node-gyp-install && ./node_modules/node-gyp-install/bin.js`

grafana-simple-sql-datasource@1.0.0 /home/install/grafana-simple-sql-datasource
└── node-gyp-install@2.2.0

node-gyp-install http request https://nodejs.org/dist/v6.11.0/node-v6.11.0.tar.gz
Error: connect ECONNREFUSED 104.20.22.46:443

I can wget the file https://nodejs.org/dist/v6.11.0/node-v6.11.0.tar.gz, also configured npm proxy to be save..

**Comment by gbrian** [comment]
Hi @c0c00n ,

Sorry for late response, how's going with this any advance?
