### ISSUE TITLE
Multiple metrics in table

### ISSUE THREAD

**Issue by AhmedAzzabi** [gbrian/grafana-simple-sql-datasource#30]
Hi, first of all thank you for this plugin, i wanted to know if let's say i have table weather with many metrics like temperature, wind, humidity, and datetime, how i can display them as metrics, do i have to create different rows ? each one is separate select :  like select 'temperature' , temperature, dt from weather then another one for raint ,.... or is there a way with single select ? thank you in advance

**Comment by buiductri** [comment]
Hi @AhmedAzzabi , have you referred #21 yet? I have an example in that thread that may suit your need. Take a look at it. ;)

**Comment by AhmedAzzabi** [comment]
Thank you very much, Yep that solves the issue basically the query have to return 3 columns Metric for metric name, Value and Time so if i have multiple metrics to show, i have to flatten them to that format.  Thanks
