### ISSUE TITLE
Grafana v5 datasource error

### ISSUE THREAD

**Issue by TryTryAgain** [gbrian/grafana-simple-sql-datasource#31]
I'm getting a success when using `curl` from the server which is running both the sql proxy and grafana, also getting success when testing in the browser. When adding that same connection string to the datasource, I'm getting the following error:

> {"err":{"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"http://sqlproxyip:666/?con=mssql://dbuser:dbpwd@dbhost/dbname","data":{"type":"test","body":null,"url":"mssql://dbuser:dbpwd@dbhost/dbname"},"retry":0,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"","xhrStatus":"error"},"cancelled":true}

I've attempted the patch here https://github.com/gbrian/grafana-simple-sql-datasource/pull/28/files without success as well. Wondering if this is an issue specific to Grafana v5? I had been running this previously on an older grafana server. 

node -v
v6.12.3

npm -v
3.10.10

Any help would be appreciated.

**Comment by mikeelindsay** [comment]
Also having this issue

**Comment by olsonnn** [comment]
Same here...

**Comment by buiductri** [comment]
I have just upgraded my dev env to Grafana v5, but it's still working. Maybe it's not due to grafana version.

FYI
node -v
v8.4.0
npm -v
5.3.0

**Comment by iShift** [comment]
after upgrade to last grafana all is ok

**Comment by TryTryAgain** [comment]
I am on the current latest Grafana v5.0.4 (commit: 7dc36ae) still experiencing this issue.

**Comment by gbrian** [comment]
Hi @TryTryAgain ,
Are you using `direct` or `proxy` datasource? Should be working fine with both, just to know if it makes a diference and we get extra information about the error.

Thanks

**Comment by iShift** [comment]
i am on direct,proxy not working

**Comment by gbrian** [comment]
Hi @iShift ,
So strange this : `...,"statusText":"","xhrStatus":"error"},"cancelled":true` Can you add some logs to check if the request get into the proxy server?
I'll check for add a `verbose` option.

@repofunding support repofunding

**Comment by repofunding** [comment]
:wave: Hi, **@repofunding** is helping @TryTryAgain on maintaining this repository. We are an open source initiative aiming to help developers on maintain their projects by using crowdfunding. 

[Why using repofunding for this project?](https://github.com/gbrian/repofunding)
### Supporting
 * You can support this repository by providing a pull request [here](https://help.github.com/articles/about-pull-requests/) 
 * Crowdfunding this issue with: 
 [![](https://img.shields.io/badge/support-$1-lightgray.svg)](https://www.paypal.me/repofunding/1) [![](https://img.shields.io/badge/support-$5-blue.svg)](https://www.paypal.me/repofunding/5) [![](https://img.shields.io/badge/support-$10-yellow.svg)](https://www.paypal.me/repofunding/10) [![](https://img.shields.io/badge/support-$20-green.svg)](https://www.paypal.me/repofunding/20)
 
 ### Important
 @repofunding status is **prototye** be patiente :wink: don't hesitate to contact us [![Join the chat at https://gitter.im/repofunding/Lobby](https://badges.gitter.im/repofunding/Lobby.svg)](https://gitter.im/repofunding/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
 
#### tags: _crowdfunding_

**Comment by TryTryAgain** [comment]
I've tried both direct and proxy, both are not working...errors below:

Direct:


    {"err":{"data":null,"status":-1,"config":{"method":"POST","transformRequest": 
    [null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"http://sqlproxyip:666/? 
    con=mssql://dbuser:dbpassword@dbhost/dbname?encrypt=true","data": 
    {"type":"test","body":null,"url":"mssql://dbuser:dbpassword@dbhost/dbname"},"retry":0,"headers": 
    {"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf- 
    8"}},"statusText":"","xhrStatus":"error"},"cancelled":true}



Proxy:


     {"data":{"error":"Internal Server Error","response":"<!DOCTYPE html>\n<html 
     lang=\"en\">\n<head>\n<meta charset=\"utf- 
     8\">\n<title>Error</title>\n</head>\n<body>\n<pre>TypeError: Cannot read property 
     &#39;1&#39; of null<br> &nbsp; &nbsp;at SQLProxyServer.getConnection 
     (/var/lib/grafana/plugins/grafana-simple-sql-datasource/dist/serverside/sqlproxyserver.js:37:44) 
    <br> &nbsp; &nbsp;at /var/lib/grafana/plugins/grafana-simple-sql- 
    datasource/dist/serverside/sqlproxyserver.js:71:13<br> &nbsp; &nbsp;at Layer.handle [as 
    handle_request] (/var/lib/grafana/plugins/grafana-simple-sql- 
    datasource/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next 
    (/var/lib/grafana/plugins/grafana-simple-sql- 
    datasource/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at 
    Route.dispatch (/var/lib/grafana/plugins/grafana-simple-sql- 
    datasource/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle 
    [as handle_request] (/var/lib/grafana/plugins/grafana-simple-sql- 
    datasource/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at 
    /var/lib/grafana/plugins/grafana-simple-sql- 
    datasource/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at param 
    (/var/lib/grafana/plugins/grafana-simple-sql- 
    datasource/node_modules/express/lib/router/index.js:354:14)<br> &nbsp; &nbsp;at param 
    (/var/lib/grafana/plugins/grafana-simple-sql- 
    datasource/node_modules/express/lib/router/index.js:365:14)<br> &nbsp; &nbsp;at 
    Function.process_params (/var/lib/grafana/plugins/grafana-simple-sql- 
    datasource/node_modules/express/lib/router/index.js:410:3) 
    </pre>\n</body>\n</html>\n","message":"Internal Server Error"},"status":500,"config": 
    {"method":"POST","transformRequest":[null],"transformResponse": 
    [null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/56","data": 
    {"type":"test","body":null,"url":null},"retry":0,"headers":{"X-Grafana-Org-Id":1,"X-Grafana- 
    NoCache":"true","Accept":"application/json, text/plain, */*","Content- 
    Type":"application/json;charset=utf-8"}},"statusText":"Internal Server 
     Error","xhrStatus":"complete"}


I'll try and get more verbose logs outside of what's presented in the web interface save and test output.

**Comment by gbrian** [comment]
Hi @TryTryAgain ,

Really rare, it looks like the "ulr" is not well formed. Error is when trying to split the "sql" from the "proxy"
https://github.com/gbrian/grafana-simple-sql-datasource/blob/6e05a9d9c57a3f6086c1a3e317d4fdc7919987b0/src/serverside/sqlproxyserver.js#L37
 
Url must be in the form:
`http://proxyserver:port/con=mssql://dbuser:dbpwd@dbhost/dbname?dbsetting=dbsettingvalue`

Please note that the `?` is used for "sql" settings. In your url is set before the `con` parameter that is from an old implementation.

Hope this helps.

**Comment by TryTryAgain** [comment]
Wow, thank you @gbrian ... removing the `?` works now for proxy, sadly I had read in other issues about that and removed it but had never tried it with proxy only direct. Now it works with proxy after removing the `?` from the url so I'm happy...fyi, doing that still doesn't allow it to work with direct, but as long as it's working I'm happy. Feel free to close this issue, unless others who have commented are not solved by this?
