### ISSUE TITLE
increase timeout

### ISSUE THREAD

**Issue by iShift** [gbrian/grafana-simple-sql-datasource#35]
how to increase  timeout for query?

**Comment by gbrian** [comment]
@iShift ,

Probably in SQL settings. Please try `http://myserver:port/con=mssql://user:name@server/database?requestTimeout=60000` (1 min timeout)

From driver's doc:
https://www.npmjs.com/package/mssql#microsoft--contributors-node-v8-driver-for-nodejs-for-sql-server
* requestTimeout - Request timeout in ms (default: 15000). NOTE: msnodesqlv8 driver doesn't support timeouts < 1 second.

Let me know if it worked.

**Comment by iShift** [comment]
@gbrian Thanks, it works!
