### ISSUE TITLE
Data points outside time range

### ISSUE THREAD

**Issue by rminni** [gbrian/grafana-simple-sql-datasource#4]
First I would just like to say thank you for all of your hard work!  If I can manage to figure this all out this project will bring a lot of value to me.

Anyways I have managed to install, connect, and query the datasource but alway get the error "Data points outside time range" the time value is always 1969-12-31 etc.  Below is my query can you please help me out? 

Select PercentFree, ServerName
From Test
Where ServerName LIKE '%Ser%' AND ReportDate >= '$from' AND ReportDate <= '$to'
Order By ReportDate asc

Thanks,

Ryan

**Comment by gbrian** [comment]
Hi @rminni,

So sorry for late response got too much work :(
Dates are a pain with SQL Server. I have to add a selector to set dates in UTC or Localtime but this is quite rare case ....

Maybe we can enable some sort of "verbose" mode to dump details from the data returned.
Let me know if you still interested on using the proxy and lets find some time for this ;)

Thanks
