### ISSUE TITLE
Logon failed for login 'test' due to trigger execution

### ISSUE THREAD

**Issue by rogercorrea** [gbrian/grafana-simple-sql-datasource#6]
I did try connect with the url: 
http://localhost:666/?con=mssql://teste:teste@172.18.86.65/Emociograma

But the sqlproxyserver returned a error for me:
{"name":"ConnectionError","message":"Logon failed for login 'teste' due to trigger execution.","code":"ELOGIN"}

I did creat one login and set permission for the database but doesn't work.
What I'm made wrong?

Thanks!

**Comment by gbrian** [comment]
Hi @rogercorrea ,

This is SQL Server relates issue, found 
https://www.sqlservercentral.com/Forums/Topic1018486-146-1.aspx

Could it be possible that you have a trigger fired for each logon?
Let me know if this helps
