### ISSUE TITLE
Issues to get the Annotations going

### ISSUE THREAD

**Issue by msurasky** [gbrian/grafana-simple-sql-datasource#9]
Hi Brian, 

First and foremost, thanks for this fantastic Grafana data source! I really appreciate the time and effort you have put here! 

Here is my problem (in case you can shed some light into it). I have tried to make the annotations work to no avail (so far).

I created a table called Annotations that look like this
CREATE TABLE Annotation (
    Id                    int identity primary key,
    Title                varchar(50),
    [Text]                varchar(1024),
    Tags                varchar(100),
    [Time]                datetime)

I then inserted some 1,000 rows. Here is a link to how the data looks like:
https://1drv.ms/i/s!AnTGGvbRh4velF7hr9hWTqxnDQR6

Finally, I went on and created the annotation in Grafana using this query:
SELECT Title as title, Text as text, Tags as tags, Time as time FROM Annotation order by time desc

After all that, I expected to see the annotations on my Dashboard, but nothing seems to appear. Is there anything I'm missing?

Thanks again!
- Martin

**Comment by gbrian** [comment]
Hi.
I'm currently far away from my laptop but checked code to refresh.
I'll try this: 
 * Firts check what's on the annotation response to see if the time info is out of the scope of the graph
 * Try '' as the time alias.

**Comment by gbrian** [comment]
Argh. Fighting against github mobile version:(

Try 'timestamp' as time field alias.
Hope this helps

**Comment by msurasky** [comment]
Changing it to timestamp did it!

Thanks for your help, we are finding your Simple SQL data source extremely useful for our graph needs!
